version: "3"

services:
  db:
    image: mysql/mysql-server:8.0
    expose:
      - "3307"
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: account
      MYSQL_ROOT_USER: root
      MYSQL_USER: account
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
    volumes:
      - ./docker/mysql/initdb.d/:/docker-entrypoint-initdb.d
      - db-vol:/var/lib/mysql

  redis:
    image: redis
    ports:
      - "6379:6379"
    expose:
      - "6379"

  app:
    build:
      context: ./
      args:
        PROFILE: local
    env_file:
      - .env
    ports:
      - "28000:8000" # for scheduler dashboard
      - "28080:8080"
      - "25005:35005" # for debugging

volumes:
  db-vol:
